// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ivXgcLob10PdSSSU4eS5tQk1gJsGGMg',
    appId: '1:931892292987:android:6483bf9d68ee0af9b4a1de',
    messagingSenderId: '931892292987',
    projectId: 'pomodoroappsync',
    databaseURL: 'https://pomodoroappsync-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pomodoroappsync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADx9RU-9NNrMgOij2UZXD77jHvNOq_AbA',
    appId: '1:931892292987:ios:91df35eecd316a53b4a1de',
    messagingSenderId: '931892292987',
    projectId: 'pomodoroappsync',
    databaseURL: 'https://pomodoroappsync-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pomodoroappsync.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGzmWpHli-Kc9038OquP-OQ6qt8Jic7EU',
    appId: '1:931892292987:web:3d1e69056df960deb4a1de',
    messagingSenderId: '931892292987',
    projectId: 'pomodoroappsync',
    authDomain: 'pomodoroappsync.firebaseapp.com',
    databaseURL: 'https://pomodoroappsync-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pomodoroappsync.firebasestorage.app',
    measurementId: 'G-JCXF4KY4ZN',
  );
}
