name: pomodoro_app
description: ポモドーロタイマーと学習管理アプリ

# アプリのバージョン
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI関連
  cupertino_icons: ^1.0.5
  fl_chart: ^0.66.0
  percent_indicator: ^4.2.2
  
  # 状態管理
  provider: ^6.0.3
  
  # データベース
  sqflite: ^2.0.3
  path: ^1.8.1
  shared_preferences: ^2.0.15
  sqflite_common_ffi: ^2.0.0  # Windows 対応用
  
  # Windows機能アクセス
  win32: ^5.0.0
  ffi: ^2.0.1
  window_manager: ^0.4.3
  
  # その他のユーティリティ
  intl: ^0.18.0
  url_launcher: ^6.1.5
#  file_picker: ^5.0.1
  file_picker: ^9.0.2
  http: ^0.13.5
#  flutter_local_notifications: ^9.7.0
  flutter_local_notifications: ^18.0.1
  
  # OSプラットフォーム検出
  platform: ^3.1.0
  audioplayers: ^6.2.0

  system_tray: ^2.0.0

  csv: ^5.0.2
  path_provider: ^2.1.0
  share_plus: ^7.0.2
  pdf: ^3.10.4
  printing: ^5.11.0
  syncfusion_flutter_charts: ^22.2.10
  image: ^4.0.0
#  uni_links: ^0.5.1
  app_links: ^6.4.0
  #device_apps: ^2.2.0  # アプリのアイコンなどの情報を取得するプラグイン
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  
  # アプリアイコン生成
  flutter_launcher_icons: ^0.12.0
  
  # スプラッシュスクリーン生成
  flutter_native_splash: ^2.2.8

# アプリアイコン設定
flutter_icons:
  #android: "launcher_icon"
  android: true
  ios: true
  image_path: "assets/icon/icon_bk.png"
  adaptive_icon_background: "#dad1c1"
  adaptive_icon_foreground: "assets/icon/icon.png"

# スプラッシュスクリーン設定
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/splash.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  
  # アセットファイル
  assets:
    - assets/images/
    - assets/icon/
    - assets/sounds/
  
  # フォント設定
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700